#!/bin/bash

# Correct plist uuid's
plistMail="/Applications/Mail.app/Contents/Info"
plistFramework="/System/Library/Frameworks/Message.framework/Resources/Info"
plistBundle="/Library/Mail/Bundles/VirgilSecurityMail.mailbundle/Contents/Info"

uuid1=$(defaults read "$plistMail" "PluginCompatibilityUUID")
uuid2=$(defaults read "$plistFramework" "PluginCompatibilityUUID")

if [[ -n "$uuid1" ]] && ! grep -q $uuid1 "${plistBundle}.plist" ;then
        defaults write "$plistBundle" "SupportedPluginCompatibilityUUIDs" -array-add "$uuid1"
fi
if [[ -n "$uuid2" ]] && ! grep -q $uuid2 "${plistBundle}.plist" ;then
        defaults write "$plistBundle" "SupportedPluginCompatibilityUUIDs" -array-add "$uuid2"
fi

plutil -convert xml1 "$plistBundle.plist"
chmod +r "$plistBundle.plist"

# Correct permissions
chmod 755 "/Library/Mail/Bundles"
chmod -R u=rwX,go=rX "/Library/Mail/Bundles/VirgilSecurityMail.mailbundle"

# Activate MAil.app bundles
case "$(sw_vers -productVersion | cut -d . -f 2)" in
	9) bundleCompVer=7 ;;
	8) bundleCompVer=6 ;;
	7) bundleCompVer=5 ;;
	6) bundleCompVer=4 ;;
	*) bundleCompVer=3 ;;
esac

defaults write "/Library/Preferences/com.apple.mail" EnableBundles -bool YES
defaults write "/Library/Preferences/com.apple.mail" BundleCompatibilityVersion -int $bundleCompVer

# Add updater job
UPDATER_PLIST="/Library/LaunchAgents/org.virgilsecurity.mail.update.plist"
UPDATER_JOB_LABEL="org.virgilsecurity.mail.update"
if [ -f "${UPDATER_PLIST}" ]; then
    su "$USER" launchctl unload -w "${UPDATER_PLIST}"
	launchctl unload -w "${UPDATER_PLIST}"
    sleep 3
	launchctl remove "${UPDATER_JOB_LABEL}"
fi

rm "${UPDATER_PLIST}"
cp "/Library/Mail/Bundles/VirgilSecurityMail.mailbundle/Contents/Resources/org.virgilsecurity.mail.update.plist" "${UPDATER_PLIST}"

su "$USER" launchctl load -w "${UPDATER_PLIST}"

# Restart Mail.app
ps -xo command -u "$USER" | grep -q '/\Mail.app/' || exit 0

echo "Restart Mail.app"

killall Mail
osascript -e "tell application \"/Applications/Mail.app\" to activate"

exit 0
